# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 律香川的蛋炒饭
email: snowyxx@126.com
description: > # this means to ignore newlines until "baseurl:"
  NOTHING AT ALL
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiaoxuenotes.com" # the base hostname & protocol for your site
twitter_username: snowyxx
github_username:  jekyll
# Build settings
markdown: kramdown
favicon: /images/favicon.png
avadar: /images/avadar.png
paginate: 20
paginate_path: "/blog/page:num/"
timezone: Asia/Shanghai
cnzz: 1257034842
duoshuo: snowyxx
gems: [jekyll-paginate]